# Generated by Django 4.2.1 on 2023-05-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "booktest",
            "0003_bookinfo_bcomment_bookinfo_bread_bookinfo_is_delete_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookinfo", old_name="is_delete", new_name="isDelete",
        ),
        migrations.RenameField(
            model_name="heroinfo", old_name="hbook", new_name="hbook_id",
        ),
        migrations.RenameField(
            model_name="heroinfo", old_name="is_delete", new_name="isDelete",
        ),
    ]
