# Generated by Django 4.2.1 on 2023-05-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booktest", "0004_rename_is_delete_bookinfo_isdelete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookinfo",
            name="bprice",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
