# Generated by Django 4.2.1 on 2023-05-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booktest", "0005_bookinfo_bprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookinfo",
            name="bprice",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
