# Generated by Django 4.2.1 on 2023-05-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booktest", "0007_rename_hbook_id_heroinfo_hbook"),
    ]

    operations = [
        migrations.RenameField(
            model_name="heroinfo", old_name="hcontent", new_name="hcomment",
        ),
    ]
