# Generated by Django 4.2.1 on 2023-05-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booktest", "0009_areas"),
    ]

    operations = [
        migrations.CreateModel(
            name="PicTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goods_pic", models.ImageField(upload_to="booktest")),
            ],
        ),
    ]
