# Generated by Django 4.2.1 on 2023-05-26 08:34

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("booktest", "0010_pictest"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gcontent", tinymce.models.HTMLField()),
            ],
        ),
    ]
